# 1 reading the data

In [56]:
import pandas as pd
import numpy as np
import sqlite3
import matplotlib.pyplot as plt

In [57]:
conn=sqlite3.connect('customer_churn.db')
q="""select name from sqlite_master where type='table'"""
tables = pd.read_sql(q, conn)

In [58]:
print(tables)

              name
0      db_customer
1  db_subscription
2       db_support

In [59]:
for table_name in tables['name']:
    df=pd.read_sql(f"select * from {table_name}",conn)
    globals()[f'df_{table_name}']=df

In [60]:
display(df_db_customer.head(),df_db_subscription.head(),df_db_support.head())

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaN,NaN,13.99,627,12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaN,NaN,6.99,210,34
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaN,NaN,22.99,1725,8
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88

,customerid,complaint_date,escalations,csat_score,col_1,comment
0,0003-MKNFE,2024-08-28 00:00:00,N,60,None,service issue
1,0003-MKNFE,2024-08-28 00:00:00,Y,10,None,demaned refund
2,0013-EXCHZ,2024-01-20 00:00:00,Y,20,None,NaN
3,0013-MHZWF,2025-03-18 00:00:00,N,90,None,guidance to renew
4,0013-SMEOE,2024-11-01 00:00:00,N,30,None,NaN

# 2 data cleaning

In [61]:
!pip install skimpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: skimpy in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (0.0.21)
Requirement already satisfied: click>=8.1.7 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (8.4.2)
Requirement already satisfied: ipykernel>=6.29.5 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (7.3.0)
Requirement already satisfied: numpy>=2.0.2 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (2.4.6)
Requirement already satisfied: pandas-stubs>=2.2.2.240807 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (3.0.3.260530)
Requirement already satisfied: pandas>=2.2.3 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (3.0.3)
Requirement already satisfied: polars>=1.17.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (1.42.1)
Requirement already satisfied: pygments>=2.18.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (2.20.0)
Requirement already satisfied: rich>=13.9.4 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (15.0.0)
Requirement already satisfied: typeguard>=4.4.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (4.5.2)
Requirement already satisfied: pyarrow>=18.0.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (25.0.0)
Requirement already satisfied: pydoclint>=0.6.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (0.9.1)
Requirement already satisfied: duckdb>=1.2.2 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (1.5.4)
Requirement already satisfied: colorama in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from click>=8.1.7->skimpy) (0.4.6)
Requirement already satisfied: comm>=0.1.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (9.15.0)
Requirement already satisfied: jupyter-client>=8.9.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (8.9.1)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (1.7.2)
Requirement already satisfied: packaging>=22 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (26.2)
Requirement already satisfied: psutil>=5.7 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (7.2.2)
Requirement already satisfied: pyzmq>=25 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (6.5.7)
Requirement already satisfied: traitlets>=5.4.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (5.15.1)
Requirement already satisfied: decorator>=5.1.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (3.0.52)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.8.1)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.8.7)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from jupyter-client>=8.9.0->ipykernel>=6.29.5->skimpy) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=4.13.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from jupyter-client>=8.9.0->ipykernel>=6.29.5->skimpy) (4.15.0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel>=6.29.5->skimpy) (4.10.0)
Requirement already satisfied: tzdata in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from pandas>=2.2.3->skimpy) (2026.2)
Requirement already satisfied: polars-runtime-32==1.42.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from polars>=1.17.1->skimpy) (1.42.1)
Requirement already satisfied: docstring_parser_fork==0.0.16 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from pydoclint>=0.6.0->skimpy) (0.0.16)
Requirement already satisfied: six>=1.5 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.9.0->ipykernel>=6.29.5->skimpy) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from rich>=13.9.4->skimpy) (4.2.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from markdown-it-py>=2.2.0->rich>=13.9.4->skimpy) (0.1.2)
Requirement already satisfied: executing>=1.2.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.2.3)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [62]:
from skimpy import skim

skim(df_db_customer)
skim(df_db_subscription)
skim(df_db_support)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 21     │ │ string      │ 7     │                                                          │
│ │ Number of columns │ 8      │ │ object      │ 1     │                                                          │
│ └───────────────────┴────────┘ └─────────────┴───────┘                                                          │
│                                                    All null                                                     │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column                                            ┃ NA                   ┃ NA %                            ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │                      pincode                      │                   21 │                             100 │  │
│ └───────────────────────────────────────────────────┴──────────────────────┴─────────────────────────────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┓  │
│ ┃           ┃    ┃          ┃           ┃          ┃           ┃          ┃ chars per ┃ words    ┃ total     ┃  │
│ ┃ column    ┃ NA ┃ NA %     ┃ shortest  ┃ longest  ┃ min       ┃ max      ┃ row       ┃ per row  ┃ words     ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━┩  │
│ │ customeri │  0 │        0 │ 0002-ORFB │ 0002-ORF │ 0002-ORFB │ 0023-UYU │        10 │        1 │        21 │  │
│ │     d     │    │          │     O     │    BO    │     O     │    PN    │           │          │           │  │
│ │   name    │  0 │        0 │   mira    │ raghvend │  Madhav   │ vishakha │      5.86 │        1 │        21 │  │
│ │           │    │          │           │    ra    │           │          │           │          │           │  │
│ │  country  │  3 │ 14.28571 │   India   │  India   │   India   │  Nepal   │         5 │     0.86 │        18 │  │
│ │           │    │ 42857142 │           │          │           │          │           │          │           │  │
│ │           │    │       86 │           │          │           │          │           │          │           │  │
│ │   state   │  0 │        0 │   Delhi   │  Uttar   │   Delhi   │  Uttar   │      8.86 │      1.1 │        23 │  │
│ │           │    │          │           │ Pradesh  │           │ Pradesh  │           │          │           │  │
│ │  gender   │  0 │        0 │    Men    │  Female  │  Female   │  Women   │      4.86 │        1 │        21 │  │
│ │    dob    │  0 │        0 │ 1982-04-1 │ 1982-04- │ 1976-09-2 │ 2004-12- │        19 │        2 │        42 │  │
│ │           │    │          │     2     │    12    │     1     │    01    │           │          │           │  │
│ │           │    │          │ 00:00:00  │ 00:00:00 │ 00:00:00  │ 00:00:00 │           │          │           │  │
│ │ interests │ 17 │ 80.95238 │    job    │  travel  │   drama   │  travel  │      4.75 │     0.19 │         4 │  │
│ │           │    │ 09523809 │           │          │           │          │           │          │           │  │
│ │           │    │        5 │           │          │           │          │           │          │           │  │
│ └───────────┴────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 21     │ │ string      │ 8     │                                                          │
│ │ Number of columns │ 11     │ │ int64       │ 2     │                                                          │
│ └───────────────────┴────────┘ │ float64     │ 1     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━┓  │
│ ┃ column              ┃ NA  ┃ NA %  ┃ mean    ┃ sd     ┃ p0    ┃ p25    ┃ p50    ┃ p75    ┃ p100   ┃ hist    ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━┩  │
│ │   monthly_charges   │   0 │     0 │   18.85 │  17.75 │  6.99 │  12.99 │  13.99 │  20.99 │  92.99 │ ▇▂   ▁  │  │
│ │        cltv         │   0 │     0 │   823.5 │  668.9 │    42 │    240 │    640 │   1150 │   2185 │ ▇▃▃▁▂▃  │  │
│ │     churn_score     │   0 │     0 │   43.29 │  32.29 │     3 │     14 │     34 │     76 │     99 │ ▇▇▃▃▃▅  │  │
│ └─────────────────────┴─────┴───────┴─────────┴────────┴───────┴────────┴────────┴────────┴────────┴─────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃           ┃    ┃           ┃          ┃           ┃          ┃           ┃ chars    ┃ words per ┃ total    ┃  │
│ ┃ column    ┃ NA ┃ NA %      ┃ shortest ┃ longest   ┃ min      ┃ max       ┃ per row  ┃ row       ┃ words    ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━┩  │
│ │ customeri │  0 │         0 │ 0002-ORF │ 0002-ORFB │ 0002-ORF │ 0023-UYUP │       10 │         1 │       21 │  │
│ │     d     │    │           │    BO    │     O     │    BO    │     N     │          │           │          │  │
│ │ subscript │  0 │         0 │ 2021-03- │ 2021-03-1 │ 2019-05- │ 2023-09-1 │       10 │         1 │       21 │  │
│ │ ion_start │    │           │    15    │     5     │    10    │     4     │          │           │          │  │
│ │   _date   │    │           │          │           │          │           │          │           │          │  │
│ │ subscript │  0 │         0 │   Paid   │ Refferal  │ Organic  │ Refferal  │     6.43 │         1 │       21 │  │
│ │ ion_type  │    │           │          │           │          │           │          │           │          │  │
│ │ renewal_d │  0 │         0 │ 2025-03- │ 2025-03-1 │ 2024-01- │ 2025-12-3 │       10 │         1 │       21 │  │
│ │    ate    │    │           │    15    │     5     │    05    │     1     │          │           │          │  │
│ │ plan_type │  0 │         0 │  Basic   │ Standard  │  Basic   │ Standard  │     6.95 │         1 │       21 │  │
│ │ contract_ │  0 │         0 │  Annual  │  Monthly  │  Annual  │  Monthly  │     6.43 │         1 │       21 │  │
│ │   type    │    │           │          │           │          │           │          │           │          │  │
│ │ cancellat │ 15 │ 71.428571 │ 2024-09- │ 2024-09-1 │ 2024-02- │ 2024-11-1 │       10 │      0.29 │        6 │  │
│ │ ion_date  │    │  42857143 │    10    │     0     │    28    │     5     │          │           │          │  │
│ │ cancellat │ 15 │ 71.428571 │   Too    │ Switched  │  Forgot  │    Too    │     19.8 │      0.86 │       18 │  │
│ │ ion_reaso │    │  42857143 │ expensiv │    to     │    to    │ expensive │          │           │          │  │
│ │     n     │    │           │    e     │ competito │  cancel  │           │          │           │          │  │
│ │           │    │           │          │     r     │  trial   │           │          │           │          │  │
│ └───────────┴────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 9      │ │ string      │ 4     │                                                          │
│ │ Number of columns │ 6      │ │ int64       │ 1     │                                                          │
│ └───────────────────┴────────┘ │ object      │ 1     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                    All null                                                     │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column                                         ┃ NA                     ┃ NA %                             ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │                     col_1                      │                      9 │                              100 │  │
│ └────────────────────────────────────────────────┴────────────────────────┴──────────────────────────────────┘  │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃ column           ┃ NA   ┃ NA %    ┃ mean     ┃ sd       ┃ p0   ┃ p25   ┃ p50   ┃ p75   ┃ p100   ┃ hist     ┃  │
│ ┡━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━┩  │
│ │    csat_score    │    0 │       0 │    40.56 │    31.67 │   10 │    20 │    30 │    60 │     90 │  ▇▇ ▃ ▅  │  │
│ └──────────────────┴──────┴─────────┴──────────┴──────────┴──────┴───────┴───────┴───────┴────────┴──────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃           ┃    ┃           ┃          ┃           ┃          ┃           ┃ chars    ┃ words per ┃ total    ┃  │
│ ┃ column    ┃ NA ┃ NA %      ┃ shortest ┃ longest   ┃ min      ┃ max       ┃ per row  ┃ row       ┃ words    ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━┩  │
│ │ customeri │  0 │         0 │ 0003-MKN │ 0003-MKNF │ 0003-MKN │ 0022-TCJC │       10 │         1 │        9 │  │
│ │     d     │    │           │    FE    │     E     │    FE    │     I     │          │           │          │  │
│ │ complaint │  0 │         0 │ 2024-08- │ 2024-08-2 │ 2024-01- │ 2025-03-1 │       19 │         2 │       18 │  │
│ │   _date   │    │           │    28    │     8     │    20    │     8     │          │           │          │  │
│ │           │    │           │ 00:00:00 │ 00:00:00  │ 00:00:00 │ 00:00:00  │          │           │          │  │
│ │ escalatio │  0 │         0 │    N     │     N     │    N     │     Y     │        1 │         1 │        9 │  │
│ │    ns     │    │           │          │           │          │           │          │           │          │  │
│ │  comment  │  5 │ 55.555555 │ service  │ guidance  │ demaned  │  service  │     14.8 │         1 │        9 │  │
│ │           │    │  55555556 │  issue   │ to renew  │  refund  │   issue   │          │           │          │  │
│ └───────────┴────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

In [63]:
conn.close()
#in customer 
# a. rename name
# b. drop colomns intrest and pincode
# c. change dob datatype
# d. data standardizarion gender
# e. fix missing value in country

In [64]:
df_db_customer.rename(columns={"name":"customer_name"},inplace=True)#inplace means it changes in same dataframe

In [65]:
df_db_customer.drop(columns=["interests","pincode"],inplace=True)

In [66]:
df_db_customer.head()

   customerid customer_name country        state  gender                  dob
0  0002-ORFBO        keshav   India  Maharashtra    Male  1982-04-12 00:00:00
1  0003-MKNFE        raghav   India    Karnataka    Male  1995-11-23 00:00:00
2  0004-TLHLJ        lalita   India        Delhi  Female  1978-02-15 00:00:00
3  0011-IGKFF         mohan   India     Nagaland    Male  2001-08-30 00:00:00
4  0013-EXCHZ          mira   India        Delhi  Female  1990-05-05 00:00:00

In [67]:
df_db_customer['dob']=pd.to_datetime(df_db_customer['dob'])

In [68]:
df_db_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     21 non-null     str
 1   customer_name  21 non-null     str
 2   country        18 non-null     str
 3   state          21 non-null     str
 4   gender         21 non-null     str
 5   dob            21 non-null     datetime64[us]
dtypes: datetime64[us](1), str(5)
memory usage: 1.8 KB

In [69]:
df_db_customer['gender'].value_counts()

gender
Female    9
Male      6
Women     3
Men       3
Name: count, dtype: int64

In [70]:
df_db_customer.loc[df_db_customer['gender']=='Women','gender']='Female'
df_db_customer.loc[df_db_customer['gender']=='Men','gender']='Male'
#df_db_customer['gender'].replace({"Women":"Female","Men":"Male"})

In [71]:
df_db_customer['gender'].value_counts()

gender
Female    12
Male       9
Name: count, dtype: int64

In [72]:
df_db_customer['country'].isnull().sum()

np.int64(3)

In [73]:
country_from_state=df_db_customer.dropna(subset=['country']).set_index('state')['country'].to_dict()

In [74]:
df['country']=df_db_customer['country'].fillna(df_db_customer['state'].map(country_from_state))

In [75]:
#in subscription
df_db_subscription.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaN,NaN,13.99,627,12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaN,NaN,6.99,210,34
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaN,NaN,22.99,1725,8
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88

In [76]:
skim(df_db_subscription)
# a. convert subscription_start_date,cancellation_date,renewal_date to date
# b.

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 21     │ │ string      │ 8     │                                                          │
│ │ Number of columns │ 11     │ │ int64       │ 2     │                                                          │
│ └───────────────────┴────────┘ │ float64     │ 1     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━┓  │
│ ┃ column              ┃ NA  ┃ NA %  ┃ mean    ┃ sd     ┃ p0    ┃ p25    ┃ p50    ┃ p75    ┃ p100   ┃ hist    ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━┩  │
│ │   monthly_charges   │   0 │     0 │   18.85 │  17.75 │  6.99 │  12.99 │  13.99 │  20.99 │  92.99 │ ▇▂   ▁  │  │
│ │        cltv         │   0 │     0 │   823.5 │  668.9 │    42 │    240 │    640 │   1150 │   2185 │ ▇▃▃▁▂▃  │  │
│ │     churn_score     │   0 │     0 │   43.29 │  32.29 │     3 │     14 │     34 │     76 │     99 │ ▇▇▃▃▃▅  │  │
│ └─────────────────────┴─────┴───────┴─────────┴────────┴───────┴────────┴────────┴────────┴────────┴─────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃           ┃    ┃           ┃          ┃           ┃          ┃           ┃ chars    ┃ words per ┃ total    ┃  │
│ ┃ column    ┃ NA ┃ NA %      ┃ shortest ┃ longest   ┃ min      ┃ max       ┃ per row  ┃ row       ┃ words    ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━┩  │
│ │ customeri │  0 │         0 │ 0002-ORF │ 0002-ORFB │ 0002-ORF │ 0023-UYUP │       10 │         1 │       21 │  │
│ │     d     │    │           │    BO    │     O     │    BO    │     N     │          │           │          │  │
│ │ subscript │  0 │         0 │ 2021-03- │ 2021-03-1 │ 2019-05- │ 2023-09-1 │       10 │         1 │       21 │  │
│ │ ion_start │    │           │    15    │     5     │    10    │     4     │          │           │          │  │
│ │   _date   │    │           │          │           │          │           │          │           │          │  │
│ │ subscript │  0 │         0 │   Paid   │ Refferal  │ Organic  │ Refferal  │     6.43 │         1 │       21 │  │
│ │ ion_type  │    │           │          │           │          │           │          │           │          │  │
│ │ renewal_d │  0 │         0 │ 2025-03- │ 2025-03-1 │ 2024-01- │ 2025-12-3 │       10 │         1 │       21 │  │
│ │    ate    │    │           │    15    │     5     │    05    │     1     │          │           │          │  │
│ │ plan_type │  0 │         0 │  Basic   │ Standard  │  Basic   │ Standard  │     6.95 │         1 │       21 │  │
│ │ contract_ │  0 │         0 │  Annual  │  Monthly  │  Annual  │  Monthly  │     6.43 │         1 │       21 │  │
│ │   type    │    │           │          │           │          │           │          │           │          │  │
│ │ cancellat │ 15 │ 71.428571 │ 2024-09- │ 2024-09-1 │ 2024-02- │ 2024-11-1 │       10 │      0.29 │        6 │  │
│ │ ion_date  │    │  42857143 │    10    │     0     │    28    │     5     │          │           │          │  │
│ │ cancellat │ 15 │ 71.428571 │   Too    │ Switched  │  Forgot  │    Too    │     19.8 │      0.86 │       18 │  │
│ │ ion_reaso │    │  42857143 │ expensiv │    to     │    to    │ expensive │          │           │          │  │
│ │     n     │    │           │    e     │ competito │  cancel  │           │          │           │          │  │
│ │           │    │           │          │     r     │  trial   │           │          │           │          │  │
│ └───────────┴────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

In [77]:
df_db_subscription['plan_type'].unique()

<ArrowStringArray>
['Standard', 'Premium', 'Basic']
Length: 3, dtype: str

In [78]:
for col in df_db_subscription.columns:
    print(col)
    print(df_db_subscription[col].unique())
    print('---------------------------------------------------------')

customerid
<ArrowStringArray>
['0002-ORFBO', '0003-MKNFE', '0004-TLHLJ', '0011-IGKFF', '0013-EXCHZ',
 '0013-MHZWF', '0013-SMEOE', '0014-BMAQU', '0015-UOCOJ', '0016-QLJIS',
 '0017-DINOC', '0017-IUDMW', '0018-NYROU', '0019-EFAEP', '0019-GFNTW',
 '0020-INWCK', '0020-JDNXP', '0021-IKXGC', '0022-TCJCI', '0023-HGHWL',
 '0023-UYUPN']
Length: 21, dtype: str
---------------------------------------------------------
subscription_start_date
<ArrowStringArray>
['2021-03-15', '2020-08-01', '2022-11-20', '2019-05-10', '2023-01-05',
 '2022-06-18', '2021-09-30', '2020-02-14', '2023-07-22', '2022-04-03',
 '2021-12-01', '2023-03-17', '2020-10-09', '2022-08-25', '2019-11-11',
 '2023-05-06', '2022-01-19', '2021-07-07', '2023-09-14', '2020-06-23',
 '2022-12-31']
Length: 21, dtype: str
---------------------------------------------------------
subscription_type
<ArrowStringArray>
['Refferal', 'Paid', 'Organic']
Length: 3, dtype: str
---------------------------------------------------------
renewal_date
<ArrowStringArray>
['2025-03-15', '2024-08-01', '2025-11-20', '2025-05-10', '2024-01-05',
 '2025-06-18', '2024-09-30', '2025-02-14', '2024-07-22', '2025-04-03',
 '2025-12-01', '2024-03-17', '2025-10-09', '2024-08-25', '2025-11-11',
 '2025-05-06', '2024-01-19', '2025-07-07', '2024-09-14', '2025-06-23',
 '2025-12-31']
Length: 21, dtype: str
---------------------------------------------------------
plan_type
<ArrowStringArray>
['Standard', 'Premium', 'Basic']
Length: 3, dtype: str
---------------------------------------------------------
contract_type
<ArrowStringArray>
['Annual', 'Monthly']
Length: 2, dtype: str
---------------------------------------------------------
cancellation_date
<ArrowStringArray>
[         nan, '2024-09-10', '2024-02-28', '2024-11-15', '2024-05-01',
 '2024-10-31', '2024-09-14']
Length: 7, dtype: str
---------------------------------------------------------
cancellation_reason
<ArrowStringArray>
[                     nan, 'Switched to competitor',          'Too expensive',
     'Not enough content', 'Poor streaming quality', 'Forgot to cancel trial']
Length: 6, dtype: str
---------------------------------------------------------
monthly_charges
[13.99 12.99  6.99 22.99 17.99  8.99  7.99 92.99 20.99 16.99]
---------------------------------------------------------
cltv
[ 627 1150  210 1725  195  720  230 1840  240  335 1610  270  980  160
 2185  640  550  840   42 1955  790]
---------------------------------------------------------
churn_score
[12 91 34  8 88 22 79  5 41 14 83 19 76  3 58 62 27 99  7 47]
---------------------------------------------------------

In [79]:
df_db_subscription['subscription_start_date']=pd.to_datetime(df_db_subscription['subscription_start_date'])
df_db_subscription['renewal_date']=pd.to_datetime(df_db_subscription['renewal_date'])
df_db_subscription['cancellation_date']=pd.to_datetime(df_db_subscription['cancellation_date'])

In [80]:
df_db_subscription.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     str
 1   subscription_start_date  21 non-null     datetime64[us]
 2   subscription_type        21 non-null     str
 3   renewal_date             21 non-null     datetime64[us]
 4   plan_type                21 non-null     str
 5   contract_type            21 non-null     str
 6   cancellation_date        6 non-null      datetime64[us]
 7   cancellation_reason      6 non-null      str
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: datetime64[us](3), float64(1), int64(2), str(5)
memory usage: 2.7 KB

In [81]:
#customer_support
df_db_support.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      str
 1   complaint_date  9 non-null      str
 2   escalations     9 non-null      str
 3   csat_score      9 non-null      int64
 4   col_1           0 non-null      object
 5   comment         4 non-null      str
 6   country         9 non-null      str
dtypes: int64(1), object(1), str(5)
memory usage: 1014.0+ bytes

In [82]:
#a. chage datatype to date of cmplaint_date
df_db_support['complaint_date']=pd.to_datetime(df_db_support['complaint_date'])

In [83]:
df_db_support.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      str
 1   complaint_date  9 non-null      datetime64[us]
 2   escalations     9 non-null      str
 3   csat_score      9 non-null      int64
 4   col_1           0 non-null      object
 5   comment         4 non-null      str
 6   country         9 non-null      str
dtypes: datetime64[us](1), int64(1), object(1), str(4)
memory usage: 843.0+ bytes

In [84]:
df_db_support.head()

,customerid,complaint_date,escalations,csat_score,col_1,comment,country
0,0003-MKNFE,2024-08-28,N,60,None,service issue,India
1,0003-MKNFE,2024-08-28,Y,10,None,demaned refund,India
2,0013-EXCHZ,2024-01-20,Y,20,None,NaN,India
3,0013-MHZWF,2025-03-18,N,90,None,guidance to renew,India
4,0013-SMEOE,2024-11-01,N,30,None,NaN,India

In [85]:
df_db_support.drop(columns=['col_1','comment'],inplace=True)

In [86]:
df_db_support.head()

   customerid complaint_date escalations  csat_score country
0  0003-MKNFE     2024-08-28           N          60   India
1  0003-MKNFE     2024-08-28           Y          10   India
2  0013-EXCHZ     2024-01-20           Y          20   India
3  0013-MHZWF     2025-03-18           N          90   India
4  0013-SMEOE     2024-11-01           N          30   India